language: node_js
node_js: "10"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron # TODO: do we need this?
    - $HOME/.cache/electron-builder # TODO: do we need this?

before_install:
  - sudo apt-get update
  - sudo apt-get install alien # we need rpm and rpmbuild

script:
- npm audit
- npm test
- npm run release

before_cache:
- rm -rf $HOME/.cache/electron-builder/wine # TODO: do we need this?

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/" # matches branch names using semantic versioning (e.g. "v0.0.1")
