language: node_js
node_js: "12"

cache: npm

before_install:
  - sudo apt-get update
  - sudo apt-get install alien # we need rpm and rpmbuild

script:
  - npm install # do install explicitly because the default (npm ci) is not sufficient
  - npm audit || true
  - npm run release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/" # matches branch names using semantic versioning (e.g. "v0.0.1")
